# Generated by Django 5.0 on 2024-01-09 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="state",
        ),
    ]
