# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# Регистрация пользователя
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "first_name": "Сергей",
  "last_name": "Попов",
  "email": "Popov@ya.ru",
  "password": "95ffff14567QERg",
  "company": "Yandex",
  "position": "Manager",
  "username": "hutz"
}

###

# Потверждение email
POST {{baseUrl}}/user/register/confirm
Content-Type: application/json

{
  "email": "Popov@ya.ru",
  "token": "6885113ae2"
}

###

# Авторизация пользователя
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "Popov@ya.ru",
  "password": "95ffff14567QERg"
}

###

# Покажи данные пользователя
GET {{baseUrl}}/user/details
Content-Type: application/json
Authorization: Token 4f35a2145e0402f5e31924171ae71498b9cc6a06

###

# Измени данные пользователя
POST {{baseUrl}}/user/details
Content-Type: application/json
Authorization: Token 4f35a2145e0402f5e31924171ae71498b9cc6a06

{
  "first_name": "Алексей",
  "last_name": "Иванов",
  "email": "che@ya.ru",
  "password": "95ffff14567QERg",
  "company": "Яндекс",
  "position": "Manager",
  "type": "buyer"
}

###


# Показать контактные данные пользователя
GET {{baseUrl}}/user/contact
Content-Type: application/json
Authorization: Token 4f35a2145e0402f5e31924171ae71498b9cc6a06

###

# Изменить контактные данные пользователя
POST  {{baseUrl}}/user/contact
Content-Type: application/json
Authorization: Token 4f35a2145e0402f5e31924171ae71498b9cc6a06

{
  "city": "Том",
  "street": "Ленина",
  "house": "200",
  "structure": "1",
  "building": "2",
  "apartment": "25",
  "phone": "+7-555-444-33-22"
}

###

# Изменить контактные данные пользователя
PUT  {{baseUrl}}/user/contact
Content-Type: application/json
Authorization: Token 4f35a2145e0402f5e31924171ae71498b9cc6a06

{
  "id": "8",
  "city": "Том",
  "street": "Ленина",
  "house": "300",
  "structure": "1",
  "building": "2",
  "apartment": "25",
  "phone": "+7-555-444-33-22"
}

###

# Удалить контактные данные пользователя
DELETE  {{baseUrl}}/user/contact
Content-Type: application/json
Authorization: Token 4f35a2145e0402f5e31924171ae71498b9cc6a06

{
  "items" : "9"
}

###

# Показать продукты
GET {{baseUrl}}/products
Content-Type: application/json

###

# Показать магазины
GET {{baseUrl}}/shops
Content-Type: application/json

###

# Показать категории
GET {{baseUrl}}/categories
Content-Type: application/json

###

# Узнать статус
GET  {{baseUrl}}/partner/state
Content-Type: application/json
Authorization: Token dcb47f10d5c351488736bc230d1aaed10d8009c1

###

# Изменить статус
POST   {{baseUrl}}/partner/state
Content-Type: application/json
Authorization: Token dcb47f10d5c351488736bc230d1aaed10d8009c1

{
  "id": "1",
  "state": "True"
}

###

# Показать заказы пользователя
GET {{baseUrl}}/partner/orders
Content-Type: application/json
Authorization: Token dcb47f10d5c351488736bc230d1aaed10d8009c1

###

# Обновление прайса от поставщика
POST {{baseUrl}}/partner/update
Content-Type: application/json
Authorization: Token dcb47f10d5c351488736bc230d1aaed10d8009c1

{
  "url": 
  "https://raw.githubusercontent.com/Lyotaaa/Final_qualification_work/main/My_project/data/shop1.yaml"
}

###

# Получить мои заказы,
GET {{baseUrl}}/order
Content-Type: application/json
Authorization: Token 3fa95a981a08e5f46c9a9645f0c69e770b699ea5

###

# Разместить заказ из корзины
POST {{baseUrl}}/order
Content-Type: application/json
Authorization: Token 3fa95a981a08e5f46c9a9645f0c69e770b699ea5

{
  "id": "2",
  "contact": "2",
  "state": "canceled"
}

###

# Получить корзину
GET {{baseUrl}}/basket
Content-Type: application/json
Authorization: Token dcb47f10d5c351488736bc230d1aaed10d8009c1

####

# Отправить в корзину
POST {{baseUrl}}/basket
Content-Type: application/json
Authorization: Token dcb47f10d5c351488736bc230d1aaed10d8009c1

{
  "items": 
[
  {
    "product_info": "3",
    "quantity": 44
  }
]
}

###

# Изменить заказ
PUT {{baseUrl}}/basket
Content-Type: application/json
Authorization: Token dcb47f10d5c351488736bc230d1aaed10d8009c1

{
  "items": 
[
  {
    "id": 10,
    "quantity": 13
  }
]
}

###

# Удалить из корзины
DELETE  {{baseUrl}}/basket
Content-Type: application/json
Authorization: Token dcb47f10d5c351488736bc230d1aaed10d8009c1

{
  "items": "10"
}